routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/blog/category/{slug?}', [App\Http\Controllers\BlogController::class, 'category'])->name('category');
Route::get('/blog/article/{slug?}', [App\Http\Controllers\BlogController::class, 'article'])->name('article');

Route::group(['prefix'=>'admin','middleware' => 'role:admin_panel'], function(){
    Route::get('/', [App\Http\Controllers\Admin\DashboardController::class,'dashboard'])->name('admin.index');
    Route::resource('/category',App\Http\Controllers\Admin\CategoryController::class,['as'=>'admin']);
    Route::resource('/article',App\Http\Controllers\Admin\ArticleController::class,['as'=>'admin']);
    Route::group(['prefix'=>'user_managment'],function(){
      Route::resource('/user',App\Http\Controllers\Admin\UserManagment\UserController::class,['as'=>'admin.user_managment']);
    });
});

Route::get('/', function () {
    return view('blog.home');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Article.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use Illuminate\Support\Str;
class Article extends Model
{
  protected $fillable = ['title', 'slug', 'description_short','description','image','image_show','meta_title','meta_description','meta_keyword', 'published', 'created_by', 'modified_by'];

  public function setSlugAttribute($value) {
    $this->attributes['slug'] = Str::slug( mb_substr($this->title, 0, 40) . "-" . \Carbon\Carbon::now()->format('dmyHi'), '-');
  }
    function categories(){
      return $this->morphToMany('App\Models\Category','categoryable');
    }
    public function scopeLastArticle($query,$count){
      return $query->orderBy("created_at","desc")->take($count)->get();
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Article;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('admin.articles.index',[
        'articles'=>Article::orderBy('created_at','desc')-> paginate(10)
      ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      if( Gate::allows('article_create')){
      return view('admin.articles.create',[
      'article'   =>[],
      'categories'=>Category::with('children')->where('parent_id','0')->get(),
      'delimiter' =>''
    ]);
  }else {
    abort(404);
  }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $article= Article::create($request->all());
      if($request->input('categories')):
        $article->categories()->attach($request->input('categories'));
      endif;
      return redirect()->route('admin.article.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
      if( Gate::allows('article_create')){
      return view('admin.articles.edit',[
      'article'=>$article,
      'categories'=>Category::with('children')->where('parent_id','0')->get(),
      'delimiter' =>''
    ]);  }else {
        abort(404);
      }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
      $article->update($request->except('slug'));
      $article->categories()->detach();
      if($request->input('categories')):
        $article->categories()->attach($request->input('categories'));
      endif;
      return redirect()->route('admin.article.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
      $article->categories()->detach();
      $article->delete();
      return redirect()->route('admin.article.index');
    }
}

resources/views/Admin/articles/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  <div class="container">
    @component('admin.components.breadcrumb')
      @slot('title') Створення статі  @endslot
      @slot('parent') Головна  @endslot
      @slot('active') Новини @endslot
    @endcomponent
    <hr>
    <form  class="form-horizontal" action="{{route('admin.article.store')}}" method="post">
      {{csrf_field()}}
      {{-- include form --}}
      @include('admin.articles.partials.form')
      <input type="hidden" name="create_by" value="{{Auth::id()}}">
    </form>
  </div>
@endsection

resources/views/Admin/articles/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  <div class="container">
    @component('admin.components.breadcrumb')
      @slot('title') Редагування статі  @endslot
      @slot('parent') Головна  @endslot
      @slot('active') Новини @endslot
    @endcomponent
    <hr>
    <form  class="form-horizontal" action="{{route('admin.article.update',$article)}}" method="post">
        <input  type="hidden" name="_method" value="put">
      {{csrf_field()}}
      {{-- include form --}}
      @include('admin.articles.partials.form')
      <input type="hidden" name="modified_by" value="{{Auth::id()}}">
    </form>
  </div>
@endsection

resources/views/Admin/articles/index.blade.php
@extends('Admin.layouts.app_admin')

@section('content')
  <div class="container">

    @component('Admin.components.breadcrumb')
      @slot('title') Список статей  @endslot
      @slot('parent') Головна  @endslot
      @slot('active') Матеріали  @endslot
    @endcomponent
    <hr>
    @if(Gate::allows('article_create'))
    <a href="{{route('admin.article.create')}}" class="btn btn-primary pull-right"><i class="fafa-plus-square-o"></i>Створити статтю</a>
    @endif
    <table class="table table-striped">
      <thead>
        <th>Назва</th>
        <th>Категорії</th>
        <th class="text-right">Дії</th>
      </thead>
      <tbody>
        @forelse ($articles as $article)
       <tr>
         <td><a href="{{route("article",$article->slug)}}">{{$article->title}}</a></td>
         <td>
          {{$article->categories()->pluck('title')->implode(", ")}}
      </td>
         <td>
           <form onsubmit="if(confirm('Видалити?')){return true}else{return false}" action="{{route('admin.article.destroy',$article)}}" method="post">
            <input type="hidden" name="_method" value="DELETE">
            {{csrf_field()}}
              @if(Gate::allows('article_edit'))
             <a href="{{route('admin.article.edit',$article)}}"><i class="fa fa-edit"></i></a>
             @endif
             @if(Gate::allows('article_delete'))
              <button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
              @endif
           </form>
          </td>
       </tr>
     @empty
       <tr>
         <td colspan="3" class="text-center"><h2>Дані відсутні</h2></td>
       </tr>
     @endforelse
      </tbody>
      <tfoot>
        <tr>
          <td colspan="3">
            <ul class="pagination  pull-right">
              {{ $articles->links('pagination::bootstrap-4')}}
            </ul>
          </td>
        </tr>
      </tfoot>
    </table>

  </div>
@endsection