routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/blog/category/{slug?}', [App\Http\Controllers\BlogController::class, 'category'])->name('category');
Route::get('/blog/article/{slug?}', [App\Http\Controllers\BlogController::class, 'article'])->name('article');

Route::group(['prefix'=>'admin','middleware' => 'role:admin_panel'], function(){
    Route::get('/', [App\Http\Controllers\Admin\DashboardController::class,'dashboard'])->name('admin.index');
    Route::resource('/category',App\Http\Controllers\Admin\CategoryController::class,['as'=>'admin']);
    Route::resource('/article',App\Http\Controllers\Admin\ArticleController::class,['as'=>'admin']);
    Route::group(['prefix'=>'user_managment'],function(){
      Route::resource('/user',App\Http\Controllers\Admin\UserManagment\UserController::class,['as'=>'admin.user_managment']);
    });
});

Route::get('/', function () {
    return view('blog.home');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use Illuminate\Support\Str;

class Category extends Model
{
  protected $fillable = ['title', 'slug', 'parent_id', 'published', 'created_by', 'modified_by'];

  public function setSlugAttribute($value) {
    $this->attributes['slug'] = Str::slug( mb_substr($this->title, 0, 40) . "-" . \Carbon\Carbon::now()->format('dmyHi'), '-');
  }

     public function children()
  {
    return $this->hasMany(self::class,'parent_id');
  }

  function articles(){
    return $this->morphedBYMany('App\Models\Article','categoryable');
  }
    public function scopeLastCategories($query,$count){
      return $query->orderBy("created_at","desc")->take($count)->get();
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('admin.categories.index',[
        'categories'=>Category::paginate(10)
      ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      if( Gate::allows('category_create')){
        return view('admin.categories.create',[
        'category'=>[],
        'categories'=>Category::with('children')->where('parent_id','0')->get(),
        'delimiter' =>''
      ]);  }else {
    abort(404);
  }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Category::create($request->all());
        return redirect()->route('admin.category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
      if( Gate::allows('category_edit')){
      return view('admin.categories.edit',[
      'category'=>$category,
      'categories'=>Category::with('children')->where('parent_id','0')->get(),
      'delimiter' =>''
    ]);  }else {
    abort(404);
  }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $category->update($request->except('slug'));
        return redirect()->route('admin.category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
          $category->delete();
          return redirect()->route('admin.category.index');
    }
}

resources/views/Admin/categories/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  <div class="container">
    @component('admin.components.breadcrumb')
      @slot('title') Створення категорії  @endslot
      @slot('parent') Головна  @endslot
      @slot('active') Категорії @endslot
    @endcomponent
    <hr>
    <form  class="form-horizontal" action="{{route('admin.category.store')}}" method="post">
      {{csrf_field()}}
      {{-- include form --}}
      @include('admin.categories.partials.form')
      <input type="hidden" name="created_by" value="{{Auth::id()}}">
    </form>
  </div>
@endsection

resources/views/Admin/categories/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

  <div class="container">
    @component('admin.components.breadcrumb')
      @slot('title') Редагування категорії  @endslot
      @slot('parent') Головна  @endslot
      @slot('active') Категорії @endslot
    @endcomponent
    <hr>
    <form  class="form-horizontal" action="{{route('admin.category.update',$category)}}" method="post">
        <input  type="hidden" name="_method" value="put">
      {{csrf_field()}}
      {{-- include form --}}
      @include('admin.categories.partials.form')
    </form>
  </div>
@endsection

resources/views/Admin/categories/index.blade.php
@extends('Admin.layouts.app_admin')

@section('content')
  <div class="container">

    @component('Admin.components.breadcrumb')
      @slot('title') Список категорій  @endslot
      @slot('parent') Головна  @endslot
      @slot('active') Категорії  @endslot
    @endcomponent
    <hr>
    @if(Gate::allows('category_create'))
    <a href="{{route('admin.category.create')}}" class="btn btn-primary pull-right"><i class="fafa-plus-square-o"></i>Створити категорію</a>
  @endif
    <table class="table table-striped">
      <thead>
        <th>Назва</th>
        <th>Публікації</th>
        <th class="text-right">Дії</th>
      </thead>
      <tbody>
        @forelse ($categories as $category)
       <tr>
         <td>{{$category->title}}</td>
         <td>{{$category->articles()->count()}}</td>
         <td>
           <form onsubmit="if(confirm('Видалити?')){return true}else{return false}" action="{{route('admin.category.destroy',$category)}}" method="post">
            <input type="hidden" name="_method" value="DELETE">
            {{csrf_field()}}
            @if(Gate::allows('category_edit'))
             <a href="{{route('admin.category.edit',$category)}}"><i class="fa fa-edit"></i></a>
           @endif
           @if(Gate::allows('category_delete'))
              <button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
            @endif
           </form>
          </td>
       </tr>
     @empty
       <tr>
         <td colspan="3" class="text-center"><h2>Дані відсутні</h2></td>
       </tr>
     @endforelse
      </tbody>
      <tfoot>
        <tr>
          <td colspan="3">
            <ul class="pagination pull-right">
              {{$categories->links('pagination::bootstrap-4')}}
            </ul>
          </td>
        </tr>
      </tfoot>
    </table>

  </div>
@endsection